[package]
name = "typst_render_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12"
#poise = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
rand = "*"
